name: Liquibase_Docker_GitHub-Hosted

on: [push]

# on:
#  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
# note the below assumes that a host path or volume is mounted into the container at ./Docker (or action will fail) !!!
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="rgba562s.instances.spawn.cc/postgres" --classpath=./changelogs/ojdbc8.jar --changeLogFile=./changelogs/changelog.sql --username=spawn_admin_YOsj --password=9eAIP9M7hfz14K1F status --verbose
    
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="rgba562s.instances.spawn.cc/postgres" --classpath=./changelogs/ojdbc8.jar --changeLogFile=./changelogs/changelog.sql --username=spawn_admin_YOsj --password=9eAIP9M7hfz14K1F --logLevel=debug update
      env:
          SPAWNCTL_ACCESS_TOKEN: ${{ secrets.LIQUIBASE_ACCESS_TOKEN }}

        
        
